# encoding: utf-8

module NPA
  AREA = {
  	#2xx
	201 => 'New Jersey (Hackensack, Jersey City, Hoboken, Bayonne, Ridgewood, Union City, Teaneck, New Milford, and most of northeastern New Jersey)',
	202 => 'Washington, D.C. (all)',
	203 => 'Connecticut (Bridgeport, Danbury, New Haven, Waterbury, and southwestern Connecticut)',
	204 => 'Manitoba (all)',
	205 => 'Alabama (Birmingham; Tuscaloosa, and parts of western and central Alabama)',
	206 => 'State of Washington (Seattle, all of Bainbridge, Mercer, and Vashon islands, Burien, Des Moines, Lake Forest Park, Normandy Park, Sea-Tac, Shoreline, Tukwila, and some small unincorporated areas adjacent to these. Also, parts of Woodway and Edmonds)',
	207 => 'Maine (all except Estcourt Station)',
	208 => 'Idaho (all)',
	209 => 'California (Stockton, Modesto, Merced, Tracy, San Andreas, and part of central California extending into central Yosemite National Park)',
	210 => 'Texas (San Antonio metropolitan area)',
	211 => 'Community Services Hotline (e.g., crisis line, United Way, etc.)',
	212 => 'New York City (Manhattan except for Marble Hill)',
	213 => 'California (Downtown Los Angeles)',
	214 => 'Texas (Dallas–Fort Worth metroplex)',
	215 => 'Pennsylvania (Philadelphia area including its suburbs in eastern Montgomery County and most of Bucks County as well as a very small portion of Berks County around the Hereford area, which is served by the Pennsburg 679 exchange.)',
	216 => 'Ohio (Cleveland area)',
	217 => 'Illinois (Springfield, Champaign, Decatur, Urbana, Lincoln, and parts of central Illinois)',
	218 => 'Minnesota (Duluth, Moorhead, Thief River Falls, Bemidji, Brainerd, International Falls, and most of northern Minnesota)',
	219 => 'Indiana (northwest => Gary, Chesterton, Crown Point, East Chicago, Hammond, Hobart, Merrillville, Michigan City, Portage, Valparaiso)',
	224 => 'Northeastern Illinois',
	225 => 'Louisiana (Baton Rouge, Donaldsonville, New Roads, White Castle, and east-central Louisiana)',
	226 => 'Ontario',
	227 => 'Maryland',
	228 => 'Mississippi (Gulfport, Biloxi, Pascagoula, Bay St. Louis, and southmost Mississippi)',
	229 => 'Georgia (Albany, Valdosta, Bainbridge, Americus, Fitzgerald, and most of southwestern Georgia)',
	231 => 'Michigan (Muskegon, Traverse City, Ludington, Petoskey, and part of northwestern Michigan)',
	234 => 'Ohio',
	236 => 'British Columbia',
	239 => 'Florida (southwest coast => all of Lee County, Collier County, the mainland part of Monroe County, including Cape Coral, Fort Myers, Naples, and Everglades)',
	240 => 'Maryland',
	242 => 'The Bahamas (all)',
	246 => 'Barbados (all)',
	248 => 'Michigan (Oakland County)',
	249 => 'Ontario => (Northeastern Ontario and Central Ontario => Greater Sudbury, Sault Ste. Marie, North Bay, etc.)',
	250 => 'British Columbia (Victoria, Prince George, Prince Rupert, Kelowna, all areas except for Vancouver); also the town of Hyder, Alaska.',
	251 => 'Alabama (Mobile County, Baldwin County, Bay Minette, Jackson, Brewton, Citronelle, and part of southwestern Alabama)',
	252 => 'North Carolina (Greenville, New Bern, Kinston, Kitty Hawk, Rocky Mount)',
	253 => 'State of Washington (Tacoma, Lakewood, Auburn, Puyallup, Enumclaw, Spanaway, and the southern suburbs of Seattle)',
	254 => 'Texas (Waco, Killeen, Temple, Belton, and Stephenville)',
	256 => 'Alabama (Huntsville, Decatur, Cullman, Gadsden, Madison, Florence, Sheffield, Tuscumbia, Fort Payne, Scottsboro, and most of northern Alabama)',
	260 => 'Indiana (Fort Wayne, New Haven, Decatur, Angola, Huntington, Wabash, and most of northeastern Indiana)',
	262 => 'Wisconsin (Racine, Kenosha, Menomonee Falls, Waukesha, and most of southeastern Wisconsin excluding Milwaukee County)',
	264 => 'Anguilla (all)',
	267 => 'Pennsylvania (Philadelphia and surrounding suburban area)',
	268 => 'Antigua and Barbuda (all)',
	269 => 'Michigan (Battle Creek, Kalamazoo, Benton Harbor, Allegan, Hastings, St. Joseph, and most of southwestern Michigan)',
	270 => 'Kentucky (Owensboro, Paducah, Bowling Green, Hopkinsville, Henderson, Elizabethtown, and most of western Kentucky)',
	272 => 'Pennsylvania (northeastern)',
	274 => 'Wisconsin',
	276 => 'Virginia (Bristol, Abingdon, Wytheville, Martinsville, Bluefield, and most of southwestern Virginia)',
	281 => 'Texas (Houston area)',
	283 => 'southwest Ohio',
	284 => 'the British Virgin Islands (all)',
	289 => 'Ontario',
	#3xx
	301 => 'Maryland (Silver Spring, Washington, D.C., suburbs, all counties which touch the Potomac River, and the towns of Hagerstown, Frederick, Rockville, Cumberland, and land line telephones in all of western Maryland)',
	302 => 'Delaware (all)',
	303 => 'Colorado (Denver, Boulder, Longmont, Aurora, Golden, Limon, Centennial; central Colorado)',
	304 => 'West Virginia',
	305 => 'Florida (all of Miami-Dade County and the Florida Keys => Miami, Miami Beach, Homestead, Coral Gables, Marathon, Key West.)',
	306 => 'Saskatchewan (all)',
	307 => 'Wyoming (all)',
	308 => 'Nebraska (North Platte, Scottsbluff, McCook, Kearney, Grand Island, and all of western Nebraska)',
	309 => 'Illinois (Peoria, Bloomington, Moline, Rock Island, Galesburg, and west-central Illinois)',
	310 => 'California (Beverly Hills, Brentwood, Malibu, Pacific Palisades, Redondo Beach, Santa Monica, Torrance, Santa Catalina Island, and the coastal areas of Los Angeles County)',
	311 => 'Local or government non-emergency use; City Hall in some localities.',
	312 => 'Illinois (downtown Chicago)',
	313 => 'Michigan (Dearborn, Detroit and its inner enclaves of Hamtramck and Highland Park)',
	314 => 'Missouri (St. Louis, St. Louis County, Florissant, Crestwood, Hazelwood, Kirwood, and surrounding suburbs of St. Louis)',
	315 => 'New York (Syracuse, Utica, Watertown, and north-central New York)',
	316 => 'Kansas (Wichita metropolitan area, McConnell Air Force Base, Augusta, El Dorado, Mulvane, and Hutchinson)',
	317 => 'Indiana (Indianapolis and immediate metro area including Carmel, Fishers, Noblesville, Greenwood, Mooresville, Beech Grove, Plainfield, Avon, and Brownsburg.)',
	318 => 'Louisiana (Shreveport, Monroe, Alexandria, Fisher, Tallulah, and most of northern Louisiana)',
	319 => 'Iowa (Cedar Rapids, Waterloo, Burlington, Iowa City, east-central, and southeastern Iowa)',
	320 => 'Minnesota (St. Cloud, Alexandria, Morris, Hutchinson, Sandstone, Appleton, Willmar and central Minnesota)',
	321 => 'Florida (Orlando, Cocoa, Melbourne, Rockledge, Titusville, St Cloud, and east-central Florida)',
	323 => 'California (part of the City of Los Angeles excluding Downtown Los Angeles, Western Los Angeles, Westwood, the San Fernando Valley, Florence, and Montebello)',
	325 => 'Texas (Abilene, San Angelo, Sweetwater, Snyder)',
	327 => 'Arkansas (Texarkana, Jonesboro, Pine Bluff, and most of southern, eastern, and northeastern Arkansas)',
	330 => 'Ohio (Akron, Canton, Youngstown, Warren, and most of northeastern Ohio)',
	331 => 'Illinois (Aurora, Naperville, Oswego, and other western suburbs of Chicago)',
	334 => 'Alabama (Montgomery, Auburn, Dothan, Enterprise, Eufaula, Opelika, Phenix City, Selma, Tuskegee and most of southeastern Alabama)',
	336 => 'North Carolina (Greensboro, Winston-Salem, Wilkesboro, Roxboro, and most of northwestern North Carolina)',
	337 => 'Louisiana (Lafayette, Lake Charles, Leesville, New Iberia, Opelousas, and most of southwestern Louisiana)',
	339 => 'Massachusetts',
	340 => 'the U.S. Virgin Islands (all)',
	341 => 'east shore of San Francisco Bay, California',
	343 => 'Ontario => (Ottawa metropolitan area and southeastern Ontario)',
	345 => 'the Cayman Islands (all)',
	347 => 'New York City',
	351 => 'Massachusetts',
	352 => 'Florida (Gainesville, Ocala, Inverness, Dunnellon, and part of central Florida)',
	356 => 'New Jersey',
	360 => 'State of Washington (Olympia, Vancouver, Bellingham, Bremerton, Port Angeles, Aberdeen, and most of western Washington except the Seattle metropolitan area)',
	361 => 'Texas (Corpus Christi, Victoria, George West, and much of South Texas)',
	364 => 'Kentucky',
	365 => 'Ontario',
	369 => 'northwest California',
	380 => 'Ohio',
	385 => 'Utah (Counties of Davis, Morgan, Salt Lake, Utah, and Weber along the Wasatch Front, including the cities of Salt Lake City, Ogden, and Provo)',
	386 => 'Florida (Daytona Beach, Lake City, Live Oak, Crescent City, and parts of northeastern Florida)',
	387 => 'Toronto, Ontario, Canada',
	#4xx
	401 => 'Rhode Island (all)',
	402 => 'Nebraska (Omaha, Lincoln, Norfolk, Superior, and most of eastern Nebraska)',
	403 => 'Alberta (Calgary, Banff, Red Deer, Medicine Hat, Lethbridge, Brooks, and most of southern Alberta)',
	404 => 'Georgia (Atlanta and the Atlanta metropolitan area inside of the Interstate 285 perimeter highway)',
	405 => 'Oklahoma (Oklahoma City, Stillwater, Edmond, Norman, Shawnee, and most of central Oklahoma)',
	406 => 'Montana (all)',
	407 => 'Florida (Orlando, Sanford, St. Cloud, Kissimmee, and part of east-central Florida)',
	408 => 'California (San Jose, Cupertino, Los Gatos, Milpitas, Mountain View, Santa Clara, Sunnyvale, and Silicon Valley)',
	409 => 'Texas (Beaumont, Galveston, Orange, Port Arthur, and Texas City)',
	410 => 'Maryland (except for St. Mary\'s County, all counties and cities which touch the Chesapeake Bay, the Atlantic Ocean, or Delaware, including Annapolis, metropolitan Baltimore, Berlin, Cambridge, Ocean City, Princess Anne, and Salisbury) as well as Howard County (Columbia)',
	411 => 'Directory Services',
	412 => 'Pennsylvania (Pittsburgh region, including McKeesport, Monroeville, Bethel Park, Penn Hills, and Ross; the area code encompasses the majority of Allegheny County and portions of Westmoreland County)',
	413 => 'Massachusetts (Springfield, Pittsfield, Holyoke, Greenfield, and most of Western Massachusetts)',
	414 => 'Wisconsin (Milwaukee County and the city of Milwaukee)',
	415 => 'California (San Francisco and most of Marin County)',
	416 => 'Ontario (the City of Toronto)',
	417 => 'Missouri (Springfield, Joplin, Branson, Lamar, Lebanon, and most of southwestern Missouri)',
	418 => 'Quebec (Quebec City, Saguenay, the Gaspé Peninsula, Côte-Nord, Chibougamau, St-Georges), Maine (Estcourt Station)',
	419 => 'Ohio (Toledo, Sylvania, Mansfield, Lima, Findlay, Sandusky, Bowling Green, and most of northwestern Ohio)',
	423 => 'Tennessee (two discontiguous portions of East Tennessee => Bristol, Johnson City, Kingsport, etc., in the northeast; and Chattanooga, Cleveland, Philadelphia, and McMinnville in the southeast)',
	424 => 'California',
	425 => 'State of Washington (the northern and eastern suburbs of Seattle => Bellevue, Everett, Edmonds, Kirkland, Redmond, Renton, Sammamish, Issaquah, and Lynnwood.)',
	430 => 'Texas',
	431 => 'Manitoba',
	432 => 'Texas (West Texas => Midland, Odessa, Big Spring, Alpine, Fort Stockton)',
	434 => 'Virginia (Charlottesville, Lynchburg, Danville, and south-central Virginia)',
	435 => 'Utah (Cedar City, Logan, Moab, Park City, Price, St. George, Tooele, Vernal and all the rest of Utah, excluding the counties of Davis, Morgan, Salt Lake, Utah, and Weber)',	
	437 => 'Ontario (Toronto metropolitan area)',
	438 => 'Quebec (Montreal metropolitan area)',
	440 => 'Ohio (surrounding Cleveland on three sides, including => Elyria, Lorain, Oberlin, Ashtabula, and most of north-central Ohio)',
	441 => 'Bermuda (all)',
	442 => 'California',
	443 => 'Maryland',
	447 => 'Illinois',
	450 => 'Quebec (central southern Quebec including the city of Laval and other suburbs of Montreal but excluding the City of Montreal)',
	456 => 'Inbound international calls for carrier-specific services',
	458 => 'Oregon (Eugene, Medford, Bend, Pendleton, Corvallis, Ontario, Burns, and all of Oregon except the metropolitan region of northwestern Oregon)',
	464 => 'Illinois',
	469 => 'Texas',
	470 => 'Georgia',
	473 => 'Grenada (all)',
	475 => 'Connecticut',
	478 => 'Georgia (Macon, Warner Robins, Swainsboro, Milledgeville, Perry, and part of central Georgia)',
	479 => 'Arkansas (Fort Smith, Fayetteville, Rogers, and most of northwestern Arkansas)',
	480 => 'Arizona (Mesa, Scottsdale, Chandler, Tempe, and the eastern Phoenix metropolitan area)',
	484 => 'Pennsylvania',
	#5xx
	500 => 'Personal Communications Services',
	501 => 'Arkansas (Little Rock, Hot Springs, and much of central Arkansas, but not Pine Bluff.)',
	502 => 'Kentucky (Louisville, Frankfort, Shelbyville, Bardstown, and most of north-central Kentucky)',
	503 => 'Oregon (Portland, Salem, Hillsboro, St. Helens, Tillamook, Astoria and most of northwestern Oregon)',
	504 => 'Louisiana (New Orleans metropolitan area)',
	505 => 'New Mexico (Albuquerque, Santa Fe, Farmington, Gallup, and all of northwestern New Mexico, and part of central New Mexico)',
	506 => 'New Brunswick',
	507 => 'Minnesota (Rochester, Mankato, Austin, Marshall, Winona and most of southern Minnesota)',
	508 => 'Massachusetts (Worcester, New Bedford, Fall River, Cape Cod, and most of southeastern Massachusetts)',
	509 => 'State of Washington (all of eastern Washington, including Spokane, Ellensburg, Pullman, the Tri-Cities area, Walla Walla, Wenatchee, and Yakima.)',
	510 => 'California (Oakland, Fremont, Hayward, Richmond, Berkeley and Alameda)',
	511 => 'Used as a state or local transportation or transit information hub. Otherwise used to direct local police non-emergency services in some communities.',
	512 => 'Texas (Austin, San Marcos, and parts of central Texas)',
	513 => 'Ohio (Cincinnati, Middletown, Hamilton, Lebanon, and parts of southern and southwestern Ohio. This area code formerly also included Dayton.)',
	514 => 'Quebec (the entire Island of Montreal, Île Perrot, and Île Bizard)',
	515 => 'Iowa (Des Moines, Ames, Fort Dodge, Jefferson, Indianola and most of north-central Iowa)',
	516 => 'New York State (Nassau County, Hempstead, Long Beach, Great Neck, etc.)',
	517 => 'Michigan (Lansing, Jackson, Charlotte, Deerfield, Addison, and most of south-central Michigan)',
	518 => 'New York State (Albany, Schenectady, Plattsburgh, Saranac Lake, Lake George, Westport, and most of northeastern New York State)',
	519 => 'Ontario (London, Windsor, Kitchener-Waterloo, Cambridge, and most of southwestern Ontario)',
	520 => 'Arizona (Tucson, Nogales, Fort Huachuca, and most of southeastern Arizona)',
	521 => 'Reserved for Personal Communications Services',
	522 => 'Reserved for Personal Communications Services',
	523 => 'Reserved for Personal Communications Services',
	524 => 'Reserved for Personal Communications Services',
	525 => 'Reserved for Personal Communications Services',
	526 => 'Reserved for Personal Communications Services',
	527 => 'Reserved for Personal Communications Services',
	528 => 'Reserved for Personal Communications Services',
	529 => 'Reserved for Personal Communications Services',
	530 => 'California (Redding, Auburn, Chico, Davis, Lake Tahoe, Placerville, Susanville, Truckee, Yreka, and most of northeastern California)',
	531 => 'Nebraska (Omaha, Lincoln, Norfolk, Superior, and most of eastern Nebraska)',
	532 => 'Reserved for Personal Communications Services',
	533 => 'Personal Communications Services',
	534 => 'Wisconsin',
	538 => 'Reserved for Personal Communications Services',
	539 => 'Oklahoma (Tulsa, Bartlesville, McAlester, Muskogee, Henryetta and northeastern Oklahoma)',
	540 => 'Virginia (Fredericksburg, Roanoke, Blacksburg, Harrisonburg, Lexington, Staunton, Winchester, and parts of north-central Virginia)',
	541 => 'Oregon (Eugene, Bend, Corvallis, Medford, Pendleton, and all of Oregon except metropolitan northwestern Oregon, including Portland, Salem, Astoria, etc.)',
	542 => 'Reserved for Personal Communications Services',
	543 => 'Reserved for Personal Communications Services',
	544 => 'Personal Communications Services',
	545 => 'Reserved for Personal Communications Services',
	547 => 'Reserved for Personal Communications Services',
	549 => 'Reserved for Personal Communications Services',
	551 => 'New Jersey',
	552 => 'Reserved for Personal Communications Services',
	553 => 'Reserved for Personal Communications Services',
	554 => 'Reserved for Personal Communications Services',
	555 => 'Reserved for directory assistance applications',
	556 => 'Reserved for Personal Communications Services',
	557 => 'Missouri',
	559 => 'California (Fresno, Hanford, Madera, Tulare, Visalia, and parts of the Central Valley of California.)',
	561 => 'Florida (Palm Beach County, including Palm Beach, West Palm Beach, Boca Raton, Boynton Beach, etc.)',
	562 => 'California (Long Beach, Whittier, Norwalk, La Habra, Lakewood, Pico Rivera, and most of southeastern Los Angeles County)',
	563 => 'Iowa (Davenport, Dubuque, Clinton, Bettendorf, and most of eastern and northeastern Iowa)',
	564 => 'State of Washington (Western Washington)',
	566 => 'Reserved for Personal Communications Services',
	567 => 'Ohio',
	569 => 'Reserved for Personal Communications Services',
	570 => 'Pennsylvania (Scranton, Wilkes-Barre, Bloomsburg, Danville, Nanticoke, Williamsport, and most of northeastern Pennsylvania)',
	571 => 'Virginia',
	573 => 'Missouri (Columbia, Jefferson City, Hannibal, Cape Girardeau, Farmington, Lake of the Ozarks, Poplar Bluff, and most of eastern Missouri excluding St. Louis County and the City of St. Louis)',
	574 => 'Indiana (South Bend, Elkhart, Goshen, and most of north-central Indiana)',
	575 => 'New Mexico (Las Cruces, Roswell, Carlsbad Caverns National Park, Socorro, Taos, Truth or Consequences; excludes central (Albuquerque and its suburbs) and northwestern New Mexico)',
	577 => 'Reserved for Personal Communications Services',
	578 => 'Reserved for Personal Communications Services',
	579 => 'Quebec (central southern Quebec including the city of Laval and other suburbs of Montreal but excluding the City of Montreal)',
	580 => 'Oklahoma (Ponca City, Ardmore, Enid, Lawton, Elk City, and most of southern and western Oklahoma)',
	581 => 'Quebec',
	582 => 'Pennsylvania',
	585 => 'New York State (Rochester, Batavia, and much of western New York State)',
	586 => 'Michigan (Warren, Sterling Heights, and Macomb County)',
	587 => 'Alberta',
	588 => 'Reserved for Personal Communications Services',
	589 => 'Reserved for Personal Communications Services',
	#6xx
	600 => 'Special telecommunications needs in Canada',
	601 => 'Mississippi (Jackson, Hattiesburg, Meridian, Natchez, Vicksburg, and most of central Mississippi)',
	602 => 'Arizona (Phoenix)',
	603 => 'New Hampshire (all)',
	604 => 'British Columbia (Greater Vancouver Regional District, Whistler)',
	605 => 'South Dakota (all)',
	606 => 'Kentucky (Ashland, Pikeville, Hazard, Somerset, London, Corbin, Maysville, and much of eastern Kentucky)',
	607 => 'New York State (Binghamton, Elmira, Cornell, Norwich, Ithaca, and most of south-central New York)',
	608 => 'Wisconsin (Madison, La Crosse, Platteville, Beloit, and most of southwestern Wisconsin)',
	609 => 'New Jersey (Trenton, Atlantic City, Princeton, and most of central & southeastern New Jersey)',
	610 => 'Pennsylvania (Chester, Lehigh Valley, Norristown, Reading; parts of southeastern Pennsylvania)',
	611 => 'Repair service for land-line telephones; customer service for most wireless carriers',
	612 => 'Minnesota (Minneapolis, Fort Snelling, St. Anthony, and Richfield)',
	613 => 'Ontario (Ottawa and eastern Ontario)',
	614 => 'Ohio Columbus and Franklin County',
	615 => 'Tennessee (Nashville, Cookeville, Lebanon, Murfreesboro, Sparta, Smyrna, Springfield, and most of Middle Tennessee)',
	616 => 'Michigan (Grand Rapids, Greenville, Holland, Ionia, Zeeland, and most of southwestern Michigan)',
	617 => 'Massachusetts (Boston, Cambridge, Quincy, Newton, Everett, and the nearby suburbs)',
	618 => 'Illinois (Carbondale, Alton, Belleville, Cahokia, Centralia, Edwardsville, Marion, Metropolis, Vandalia, and most of southern Illinois)',
	619 => 'California (southern half of San Diego, California city, and southern and eastern suburbs including Chula Vista, National City, El Cajon, La Mesa, Lemon Grove)',
	620 => 'Kansas (southern Kansas not including the Wichita Metropolitan Area and Hutchison.)',
	623 => 'Arizona (part of Maricopa County, including Glendale, Buckeye, Goodyear, Peoria, Sun City, and the western half of Phoenix)',
	626 => 'California (Pasadena, Arcadia, Clermont, Covina, El Monte, La Cañada-Flintridge, La Puente, Monrovia, the San Gabriel Valley, Upland, and West Covina)',
	627 => 'the northern California coast',
	628 => 'San Francisco',
	630 => 'Illinois (Western suburbs of Chicago, including DuPage, central and southern Kane, northern Kendall, far northern Will, and small portions of Cook Counties. Includes Aurora, Naperville, Wheaton, Downers Grove, Elmhurst, Lombard, Glen Ellyn, Bloomingdale, Carol Stream, Addison, Glendale Heights, Bartlett, Hanover Park, Streamwood, Bolingbrook, St. Charles, Geneva, Batavia, Sugar Grove, Oswego, Yorkville, Plano, Darien, Woodridge, Hinsdale, Oak Brook, Lemont, and other suburbs west of Chicago)',
	631 => 'New York State (Suffolk County on Long Island)',
	636 => 'Missouri (St. Charles, Chesterfield, Union, Troy, and parts of east-central Missouri)',
	639 => 'Saskatchewan',
	641 => 'Iowa (Mason City, Oskaloosa, Creston, Pella, Ottumwa, Britt, Clear Lake, Fairfield, and parts of central Iowa)',
	646 => 'New York State (Borough of Manhattan, except for Marble Hill on the mainland of New York)',
	647 => 'Ontario',
	649 => 'the Turks and Caicos Islands (all)',
	650 => 'California (Palo Alto, Redwood City, Menlo Park, Mountain View, San Mateo, Santa Clara, Stanford, South San Francisco)',
	651 => 'Minnesota (St. Paul, Eagan, Lindstrom, Red Wing, Hastings, Stillwater and part of east-central Minnesota)',
	657 => 'California',
	658 => 'Jamaica',
	659 => 'Alabama',
	660 => 'Missouri (Sedalia, Kirksville, Maryville, Mexico, Whiteman Air Force Base, and part of north-central Missouri)',
	661 => 'California (Bakersfield, Lancaster, Palmdale, Edwards Air Force Base, and parts of Kern County, and Los Angeles County)',
	662 => 'Mississippi (Tupelo, Columbus, Corinth, Greenville, Greenwood, Starkville, and most of northern Mississippi)',
	664 => 'Montserrat (all)',
	667 => 'Maryland',
	669 => 'California',
	670 => 'Northern Mariana Islands',
	671 => 'Guam',
	672 => 'British Columbia',
	678 => 'Georgia',
	679 => 'Michigan',
	681 => 'West Virginia',
	682 => 'Texas',
	684 => 'American Samoa',
	689 => 'Florida',
	#7xx
	700 => 'Long Distance carrier use for pre-subscribing phone numbers',
	701 => 'North Dakota (all)',
	702 => 'Nevada (almost all of Clark County, including all of the Las Vegas Valley, including Henderson and Boulder City)',
	703 => 'Virginia (Northern Virginia => mostly the suburbs of Washington, D.C., including Alexandria, Arlington County, Fairfax County, Prince William County, and eastern Loudoun County)',
	704 => 'North Carolina (Charlotte, Concord, Gastonia, Salisbury, and much of south-central North Carolina)',
	705 => 'Ontario => (Northeastern Ontario and Central Ontario => Greater Sudbury, Sault Ste. Marie, North Bay, etc.)',
	706 => 'Georgia (Athens, Augusta, Columbus, Carrollton, Carroll County, Cartersville, Dalton, Rome, and much of northwestern, northeastern and eastern Georgia, with an exclave in western Georgia)',
	707 => 'California (Vallejo, Crescent City, Eureka, Redwoods National Park, Santa Rosa, Ukiah, and most of northwestern California)',
	708 => 'Illinois (Western and southern portions of suburban Cook County and far eastern sections of Will County. Includes Beecher, Berwyn, Brookfield, Bridgeview, Burbank, Calumet City, Chicago Heights, Cicero, Dolton, Elmwood Park, Evergreen Park, Franklin Park, Harvey, Hazel Crest, Homer Glen, Homewood, La Grange, Lansing, Matteson, Maywood, Melrose Park, Mokena, Monee, Oak Forest, Oak Park, Orland Park, Palos Hills, Park Forest, Peotone, Tinley Park, University Park, and other southern and near western suburbs of Chicago)',
	709 => 'Newfoundland and Labrador',
	710 => 'U.S. Government Special Services',
	711 => 'Telecommunications device for the deaf/Relay Service for TTY to Voice and Voice to TTY',
	712 => 'Iowa (Sioux City, Council Bluffs, Denison, and most of western Iowa)',
	713 => 'Texas (Houston area)',
	714 => 'California (Orange County => Anaheim, Fullerton, Garden Grove, Huntington Beach, Irvine, Newport Beach, Orange, Santa Ana, etc.)',
	715 => 'Wisconsin (Wausau, Eau Claire, Rhinelander, and most of northern Wisconsin)',
	716 => 'New York State (Buffalo, Niagara Falls, Olean, and parts of western New York)',
	717 => 'Pennsylvania (Harrisburg, Gettysburg, Lancaster, York and most of south-central Pennsylvania)',
	718 => 'New York State (New York City except for Manhattan, but this area code includes Marble Hill, a neighborhood of the Borough of Manhattan located on the mainland)',
	719 => 'Colorado (Colorado Springs, Pueblo, Florence, Leadville, Limon, Trinidad, La Junta, and most of southeastern Colorado)',
	720 => 'Colorado',
	721 => 'Sint Maarten',
	724 => 'Pennsylvania (Washington, Greensburg, Indiana, New Castle, Uniontown, Butler, and the majority of Southwestern Pennsylvania outside of Pittsburgh\'s Allegheny County)',
	727 => 'Florida (all of Pinellas County including St. Petersburg, Clearwater, Dunedin, Palm Harbor, Tarpon Springs, and the coastal parts of Pasco County)',
	730 => 'Illinois',
	731 => 'Tennessee (most of West Tennessee — excluding Metropolitan Memphis and Shelby County, but including Dyersburg, Jackson, Martin, Paris, Union City, and Crockett County)',
	732 => 'New Jersey (New Brunswick, Lakewood, Neptune, Fort Dix, and most of east-central New Jersey—but not Atlantic City)',
	734 => 'Michigan (Ann Arbor, Hell, Monroe, Plymouth, Romulus, Wayne, Ypsilanti, and the southwestern suburbs of Detroit)',
	737 => 'Texas',
	740 => 'Ohio (Suburban Columbus, central Ohio outside of Franklin County, excluding the Marysville area, together with southeastern Ohio => Athens, Lancaster, Cambridge, Delaware, Ironton, Marietta, Mt. Vernon, Newark, Portsmouth, Steubenville, Washington Court House, and Zanesville)',
	742 => 'Ontario, Canada',
	747 => 'California (Los Angeles County, San Fernando Valley)',
	754 => 'Florida',
	757 => 'Virginia (Part of Hampton Roads and the Eastern Shore of Virginia)',
	758 => 'Saint Lucia (all)',
	760 => 'California (Bishop, Ridgecrest, Barstow—eastern portions of San Bernardino County and Riverside County, including Palm Springs, Palm Desert, and Indio—Imperial County, and parts of northern and eastern San Diego County, including Oceanside and other northern suburbs of San Diego, California)',
	761 => 'Palm Beach County, Florida',
	762 => 'Georgia',
	763 => 'Minnesota (Brooklyn Park, Plymouth, Maple Grove, Monticello, Elk River, Fridley, Blaine, and the northwest suburban area of Minneapolis)',
	764 => 'western San Francisco Bay, including Contra Costa County',
	765 => 'Indiana (Lafayette, Marion, Muncie, Richmond, West Lafayette, and most of central Indiana excluding Indianapolis and immediate suburbs)',
	767 => 'Commonwealth of Dominica (all)',
	769 => 'Mississippi',
	770 => 'Georgia (Marietta, Carrollton, Gainesville, Jonesboro, Lawrenceville, Roswell, Stone Mountain, and much of north-central Georgia outside of Atlanta\'s Interstate 285 Perimeter Highway)',
	772 => 'Florida (Fort Pierce, Port Saint Lucie, Sebastian, Stuart, and Vero Beach, and all of Indian River County and Martin County)',
	773 => 'Illinois (City of Chicago, excluding downtown)',
	774 => 'Massachusetts',
	775 => 'Nevada (Carson City, Reno, Elko, Ely, Sparks, Winnemucca, Great Basin National Park, Naval Air Station Fallon, and all of Nevada except for most of Clark County in southernmost Nevada)',
	778 => 'British Columbia (all)',
	779 => 'Illinois',
	780 => 'Alberta (Edmonton, Jasper, Grande Prairie, Peace River, and all of northern Alberta)',
	781 => 'Massachusetts (Saugus, Norwood, Waltham Woburn, and other suburbs of Boston along Route 128)',
	782 => 'Nova Scotia and Prince Edward Island',
	784 => 'Saint Vincent and the Grenadines (all)',
	785 => 'Kansas (Topeka, Salina, Colby, Lawrence, Manhattan, and all of northern and central Kansas not including the Kansas City Metropolitan Area)',
	786 => 'Florida (Miami-Dade County and the Florida Keys)',
	787 => 'Puerto Rico',
	#8xx
	800 => 'Toll-free telephone service',
	801 => 'Utah (Counties of Davis, Morgan, Salt Lake, Utah, and Weber along the Wasatch Front, including the cities of Salt Lake City, Ogden, and Provo)',
	802 => 'Vermont (all)',
	803 => 'South Carolina (Columbia, Rock Hill, Sumter, Aiken, and most of central South Carolina)',
	804 => 'Virginia (the Richmond Metropolitan Area, including Petersburg; also the Northern Neck and Middle Peninsula)',
	805 => 'California (Ventura County, San Luis Obispo County, Santa Barbara County, Atascadero, Lompoc, Ojai, Oxnard, Pismo Beach, San Buenaventura, Santa Maria, Simi Valley, and Vandenberg Air Force Base)',
	806 => 'Texas (Lubbock, Amarillo, Canadian, Canyon, Dalhart, and the entire Texas Panhandle)',
	807 => 'Ontario (Northwestern Ontario => Thunder Bay, Kenora, Dryden, Greenstone)',
	808 => 'Hawaii (covers all of the Hawaiian Islands to Midway Atoll, and major Hawaiian cities including Honolulu, Kailua, Mililani, Haleiwa, Hilo, Kahului, Lihue, etc. Area code also includes Wake Island)',
	809 => 'Dominican Republic',
	810 => 'Michigan (Port Huron, Flint, Lapeer, and Michigan "Thumb")',
	811 => 'Mobile customer service on some North American cellular carriers, also used as a 9-1-1 like emergency number to handle distress calls in much of Jamaica',
	812 => 'Indiana (Southern Indiana, including Bloomington, Evansville, Terre Haute, Columbus, Jeffersonville, Lawrenceburg, Madison, and New Albany)',
	813 => 'Florida (all of Hillsborough County, including Tampa and its suburbs, MacDill Air Force Base, and Plant City; and also the inland areas of Pasco County)',
	814 => 'Pennsylvania (Erie, State College, Altoona, Clearfield, Emporium, Johnsonburg, Johnstown, Meyersdale, Ridgway, Somerset, and most of northwestern and parts of central Pennsylvania)',
	815 => 'Illinois (much of northern Illinois outside Chicago & its immediate surrounding suburbs. Includes Rockford and its suburbs, Belvidere, La Salle, Peru, DeKalb, Sycamore, Freeport, Dixon, Sterling, Rock Falls, Ottawa, Morris, Princeton, Mendota, Rochelle, Sandwich, Streator, Pontiac, Kankakee, and some outlying Chicago suburbs such as Harvard, McHenry, Crystal Lake, Woodstock, Plainfield, Joliet, Romeoville, Lockport, New Lenox, Frankfort, Minooka, Channahon, and Shorewood)',
	816 => 'Missouri (Kansas City, St Joseph, Independence, Harrisonville, and parts of west-central Missouri)',
	817 => 'Texas (Fort Worth, Arlington, Grand Prairie, Grandview, Weatherford)',
	818 => 'California => the San Fernando Valley of Los Angeles County, including Burbank, Canoga Park, Encino, Glendale, North Hollywood, Northridge, Panorama City, Reseda, San Fernando, Sylmar, Tarzana, Van Nuys, and Woodland Hills)',
	819 => 'Quebec (Abitibi-Témiscamingue, Estrie, Mauricie, Outaouais, Sherbrooke, and Trois-Rivieres)',
	822 => 'reserved for future toll-free expansion',
	825 => 'reserved for future usage in Alberta.',
	828 => 'North Carolina (Asheville, Franklin, Hickory, Murphy, Waynesville, and parts of western North Carolina)',
	829 => 'the Dominican Republic',
	830 => 'Texas (Del Rio, Kerrville, Eagle Pass, Fredericksburg, New Braunfels, and part of the Rio Grande Valley)',
	831 => 'California (Monterey, Salinas, Monterey County, Hollister, and Santa Cruz)',
	832 => 'Texas',
	833 => 'reserved for future toll-free expansion',
	843 => 'South Carolina (Charleston, Florence, Hilton Head Island, Myrtle Beach, Charleston Air Force Base, and most of southeastern South Carolina)',
	844 => 'reserved for future toll-free expansion',
	845 => 'New York State (Dutchess, Orange, Putnam, Rockland, Sullivan, and Ulster Counties in southeastern New York State. Includes => Poughkeepsie, Middletown, Kingston, West Point, Newburgh, and the Catskill Mountains west to Margaretville)',
	847 => 'Illinois (North and northwest suburbs of Chicago, including Lake, northern Cook, northern Kane, and extreme southeastern McHenry Counties. Includes Evanston, Skokie, Niles, Park Ridge, Des Plaines, Mount Prospect, Arlington Heights, Palatine, Wheeling, Buffalo Grove, Barrington, Elk Grove Village, Schaumburg, Hoffman Estates, Elgin, Carpentersville, Algonquin, Lake in the Hills, Huntley, Hampshire, Cary, Lake Zurich, Fox Lake, Round Lake Beach, Antioch, Gurnee, Waukegan, Zion, Lake Forest, Vernon Hills, Libertyville, Mundelein, Northbrook, Glenview, Deerfield, Highland Park, Wilmette, Winnetka, etc.)',
	848 => 'New Jersey',
	849 => 'the Dominican Republic',
	850 => 'northwestern Florida (Appalachicola, Pensacola, Tallahassee, Quincy, Panama City, Naval Air Station Pensacola, Eglin Air Force Base, and all of the Florida Panhandle)',
	855 => 'reserved for future toll-free expansion',
	856 => 'New Jersey (Cherry Hill, Camden, Millville, Vineland, and most of southwestern New Jersey)',
	857 => 'Massachusetts (Boston, Cambridge, Quincy, Newton, Everett, and the nearby suburbs)',
	858 => 'Southern California (the northern half of San Diego, California city and some northern suburbs)',
	859 => 'Kentucky (Lexington, Richmond, Danville, Covington, Florence, and northernmost Kentucky)',
	860 => 'Connecticut (Hartford, Bristol, Norwich, and northern and eastern Connecticut)',
	862 => 'New Jersey',
	863 => 'Florida (Lakeland, Bartow, Sebring, Winter Haven in south-central Florida)',
	864 => 'South Carolina (Greenville, Spartanburg, Anderson, Clemson, and most of northwestern South Carolina)',
	865 => 'Tennessee (Knoxville, Alcoa, Athens, Clinton, Crossville, Dayton, Gatlinburg, Loudon, Maryville, Newport, Oak Ridge, Oliver Springs, Pigeon Forge, Rockwood, Sweetwater, etc., in East Tennessee)',
	866 => 'Toll-free telephone service',
	867 => 'Yukon, Northwest Territories, and Nunavut',
	868 => 'Trinidad and Tobago (all)',
	869 => 'Saint Kitts and Nevis (all)',
	870 => 'Arkansas (Texarkana, Jonesboro, Pine Bluff, and southern, eastern, and northeastern Arkansas)',
	872 => 'Illinois',
	873 => 'Quebec',
	876 => 'Jamaica (all)',
	877 => 'Toll-free telephone service',
	878 => 'Pennsylvania',
	880 => 'Toll-free telephone service',
	881 => 'Toll-free telephone service',
	882 => 'Toll-free telephone service',
	888 => 'Toll-free telephone service',
	#9xx
	900 => 'premium-rate telephone numbers',
	901 => 'Tennessee (Memphis, Covington, Germantown, Somerville, and extreme southwestern Tennessee, mostly in Shelby County)',
	902 => 'Nova Scotia and Prince Edward Island',
	903 => 'Texas (Tyler, Sherman, Longview, Marshall, Palestine, Jacksonville, Carthage, and Northeast Texas)',
	904 => 'Florida (Jacksonville, St. Augustine, Starke, and most of northeastern Florida)',
	905 => 'Ontario (Niagara Falls Region, Hamilton, St. Catharines, suburbs of the Greater Toronto Area, and southeastern Ontario)',
	906 => 'Michigan (Upper Peninsula of Michigan => (Sault Ste. Marie, Escanaba, Houghton, Iron Mountain, Marquette, Menominee, etc.)',
	907 => 'all of Alaska excluding the lone town of Hyder',
	908 => 'New Jersey (Alpha, Washington, Elizabeth, Warren, Plainfield, and west-central New Jersey)',
	909 => 'California (western portions of San Bernardino County, and parts of Los Angeles County and Riverside County, including Fontana, Pomona, Chino Hills, Claremont, Chino, Ontario, Redlands)',
	910 => 'North Carolina (Fayetteville, Wilmington, Fort Bragg, Seymour Johnson Air Force Base, Jacksonville, Lumberton and much of southeastern North Carolina)',
	911 => 'Emergency Services',
	912 => 'Georgia (Savannah, Statesboro, Vidalia, Waycross, Brunswick, Douglas, and southeastern Georgia)',
	913 => 'Kansas (Kansas City, Kansas, Overland Park, Leavenworth, Ft. Leavenworth, parts of eastern Kansas)',
	914 => 'New York State (Westchester County)',
	915 => 'Texas (all of El Paso County and portions of Hudspeth County)',
	916 => 'California (the Sacramento Metropolitan Area)',
	917 => 'New York State (New York City; cellular telephones)',
	918 => 'Oklahoma (Tulsa, Bartlesville, McAlester, Muskogee, Henryetta and northeastern Oklahoma)',
	919 => 'North Carolina (Raleigh, the state capital city, Durham, Chapel Hill, Goldsboro, and part of north-central North Carolina)',
	920 => 'Wisconsin (Appleton, Sheboygan, Oshkosh, Green Bay, Manitowoc, Marquette, Fond du Lac, and parts of eastern Wisconsin—but not Milwaukee County)',
	925 => 'California (Livermore, Concord, Pleasant Hill, Walnut Creek, Martinez, Pleasanton and Dublin, just east of San Francisco Bay. Much of this area is served by the Bay Area Rapid Transit system, including Concord.)',
	928 => 'Arizona (Flagstaff, Kingman, Lake Havasu City, Page, Payson, Prescott, Tuba City, Williams, Winslow, Window Rock, Yuma, and most of northern and western Arizona, including the Grand Canyon National Park, the Lower Colorado River Valley, and the Navajo Nation)',
	929 => 'New York',
	931 => 'Tennessee (Middle Tennessee, excluding the Nashville Metropolitan Area => Clarksville, Manchester, Columbia, Cookeville, Sparta)',
	935 => 'San Diego',
	936 => 'Texas (Nacogdoches, Lufkin, Conroe, Huntsville, Center, and Southeast Texas)',
	937 => 'Ohio (Dayton, Marysville, Springfield, Hillsboro, and southwestern Ohio excluding the Cincinnati Metropolitan Area)',
	938 => 'Alabama (Huntsville, Anniston, Cullman, Decatur, Florence, Ft. Payne, Gadsden, Madison, Sheffield, Tuscumbia)',
	939 => 'Puerto Rico',
	940 => 'Texas (Denton, Wichita Falls, Decatur, Gainesville, Vernon, etc.)',
	941 => 'Florida (Gulf Coast immediately south of Tampa Bay => all of Manatee County, Sarasota County, and Charlotte County; includes Bradenton, Port Charlotte, Sarasota, and Punta Gorda)',
	947 => 'Michigan',
	949 => 'California (Irvine, Lake Forest, Mission Viejo, Newport Beach, Corona del Mar, and part of southern Orange County)',
	950 => 'Used internally for carrier access',
	951 => 'California (western Riverside County, including Riverside, Corona, Lake Elsinore, Mira Loma, Moreno Valley, Sun City, Temecula, Winchester, Lakeview, etc.)',
	952 => 'Minnesota (Bloomington, Eden Prairie, Edina, Minnetonka, Chaska, and the southwest suburban Minneapolis area)',
	954 => 'Florida (all of Broward County => Fort Lauderdale, Hollywood, Coral Springs, etc.)',
	956 => 'Texas (Laredo, Harlingen, Brownsville, McAllen, and southmost Texas)',
	959 => 'Connecticut',
	970 => 'Colorado (Grand Junction, Aspen, Durango, Estes Park, Fort Collins, Frisco, Glenwood Springs, Greeley, Purgatory, Steamboat Springs, Telluride, Vail, Rocky Mountain National Park, Dinosaur National Monument, and most of north-central, south-central, and western Colorado)',
	971 => 'Oregon (Portland, Salem, Hillsboro, Beaverton, and most of northwestern Oregon)',
	972 => 'Texas',
	973 => 'New Jersey (Newark, Paterson, and most of northeastern New Jersey)',
	975 => 'Missouri',
	978 => 'Massachusetts (Fitchburg, Lowell, Lawrence, Peabody, and northeastern Massachusetts)',
	979 => 'Texas (Wharton, Bryan, Bay City, College Station, Lake Jackson, La Grange, and southeastern Texas)',
	980 => 'North Carolina',
	984 => 'North Carolina',
	989 => 'Michigan (Alpena, Mt. Pleasant, Bay City, Saginaw, Midland, Owosso, and part of central Michigan)'
  }

  def self.find(code)
  	AREA[code]
  end

  def self.exist?(code)
  	AREA.key?(code)
  end

  def self.of_number(number)
  	number = number.to_s.gsub(/[^0-9]/, '')

  	case number.length
  	when 10
  		area_code = number[0,3].to_i
  	when 11
  		area_code = number[1,3].to_i
  	else
  		return nil
  	end

  	npa = find(area_code)
  	return npa, area_code if npa
  end

  class << self; alias_method(:exists?, :exist?); end;
end